name: Build Vite React App

on:
  pull_request:
    branches:
      - main # Trigger workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Update Node.js to a version >= 18

    - name: Navigate to frontend and install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build the app
      working-directory: ./frontend
      run: npm run build

    - name: Verify build output exists
      working-directory: ./frontend
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed: dist directory not found."
          exit 1
        fi
