name: Build Vite React App

on:
  pull_request: # Trigger workflow on pull requests
    branches:
      - main # Specify the branch to enforce the checks

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Ensure you use a compatible Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Verify build output exists
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed: dist directory not found."
          exit 1
        fi
